[net]
git-fetch-with-cli = true

[build]
rustc-wrapper = "sccache"
target-dir = ".cache/cargo/target"

[alias]
u = 'update'
n = 'new --offline'
f = 'fmt --all'
d = "doc --offline"
b = 'build --offline'
bu = 'build'
t = 'nextest run --workspace'
tnc = 'nextest run --workspace --no-capture'
c = 'clippy --tests --workspace'
clr = 'clean'
au = 'audit'
gl = 'generate-lockfile'
